name: docker
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Tag to apply to the docker image"
        required: true
        default: "latest"
jobs:
  docker-release:
    runs-on: 4-core-runners-for-docker
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: fwai
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            recipes_commit=${{ github.sha }}
          context: ./recipes/docker/text
          file: ./recipes/docker/text/Dockerfile
          push: true
          # platforms inherited from NGC
          platforms: linux/amd64,linux/arm64
          tags: |
            fwai/cookbook:${{ inputs.version || 'latest' }}
            fwai/cookbook:${{ github.sha }}
