#!/usr/bin/env python3
"""Serverless DPO (Direct Preference Optimization) -- a self-contained,
Tinker-style loop.

This example runs preference training against Fireworks **serverless
training**: you connect to a shared, already-running pooled trainer and get
back a Tinker-compatible training client. There is nothing to provision.

It is the Fireworks port of Tinker's DPO recipe
(``tinker_cookbook/preference/train_dpo.py``). The loop is identical:

    service = FiretitanServiceClient(base_url=".../training/v1/serverless")
    training_client = service.create_lora_training_client(base_model, rank)
    # Reference = frozen snapshot of the step-0 weights (zero-init LoRA, so
    # this IS the base model) -- the same anchor Tinker uses.
    ref_path = training_client.save_weights_for_sampler("dpo-ref").result().path
    reference_client = service.create_sampling_client(model_path=ref_path)
    for step in range(steps):
        # datums interleaved [chosen_0, rejected_0, chosen_1, rejected_1, ...]
        ref_logprobs = [reference_client.compute_logprobs(seq) for seq in batch]
        training_client.forward_backward_custom(datums, dpo_loss_fn).result()
        training_client.optim_step(adam).result()

The loss (Rafailov et al., 2023) is the shared ``make_batch_dpo_loss_fn`` --
the same math the managed ``recipes/dpo_loop.py`` uses::

    L = -log sigmoid(beta * [(pi_chosen - ref_chosen) - (pi_rejected - ref_rejected)])

The default dataset is UltraFeedback binarized preferences (same source as
Tinker's ultrafeedback DPO builder), generated by ``prepare_data.py``.
``margin`` and ``accuracy`` should climb; ``dpo_loss`` should fall from
~0.693 (ln 2).

Usage::

    export FIREWORKS_API_KEY=fw_...
    python -m examples.serverless_dpo.prepare_data     # one-time data download
    python -m examples.serverless_dpo.ultrafeedback_dpo

    # resume a previous run's checkpoint in a brand-new process
    python -m examples.serverless_dpo.ultrafeedback_dpo \\
        --resume-from <account>/<run-id>/<checkpoint-name>
"""

from __future__ import annotations

import argparse
import json
import os
import time
import warnings
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import tinker
from fireworks.training.sdk import FireworksClient, FiretitanServiceClient
from tinker_cookbook.renderers import get_text_content
from tinker_cookbook.tokenizer_utils import get_tokenizer

try:  # Load FIREWORKS_API_KEY / FIREWORKS_BASE_URL from a local .env if present.
    from dotenv import load_dotenv

    load_dotenv()
except ImportError:
    pass

from training.utils import WandBConfig, setup_wandb, wandb_finish, wandb_log
from training.utils.data import normalize_preference_row
from training.utils.losses import make_batch_dpo_loss_fn
from training.utils.supervised import (
    build_renderer,
    render_preference_pair,
    resolve_renderer_name,
)

HERE = Path(__file__).resolve().parent
DEFAULT_DATASET = HERE / "preference_train.jsonl"

# Promotable checkpoint ids embed the run id against a 63-character limit,
# so checkpoint names must stay short.
MAX_CHECKPOINT_NAME_LEN = 17


@dataclass
class Config:
    """Everything you might want to tune. Edit the ``__main__`` block below."""

    # --- What to train ------------------------------------------------------
    base_model: str = "accounts/fireworks/models/kimi-k3"
    # HuggingFace tokenizer matching ``base_model``.
    tokenizer_model: str = "moonshotai/Kimi-K3"
    # Leave "" to auto-pick the recommended chat renderer for the tokenizer.
    renderer_name: str = ""
    dataset: str = str(DEFAULT_DATASET)
    lora_rank: int = 8
    # Serverless has no training shape from which to infer this bound.
    max_seq_len: int = 32768

    # --- DPO loop shape -----------------------------------------------------
    steps: int = 8
    # Preference *pairs* per optimizer step (each pair is 2 datums).
    batch_size: int = 4
    learning_rate: float = 1e-5
    # KL-penalty coefficient. Higher = stay closer to the reference model.
    dpo_beta: float = 0.1
    # Max reference compute_logprobs calls in flight at once.
    ref_concurrency: int = 8

    # --- Checkpointing ------------------------------------------------------
    # Save a full trainer-state checkpoint (weights + optimizer) every N
    # steps; 0 disables. These are what --resume-from consumes.
    dcp_save_interval: int = 4
    checkpoint_name: str = "dpo"
    # Sampler checkpoint saved at the end of the run, and the one promoted.
    final_checkpoint_name: str = "dpo-final"
    # Sampler checkpoint holding the step-0 weights, served as the frozen
    # DPO reference model for the whole run.
    reference_checkpoint_name: str = "dpo-ref"
    # Resume from a checkpoint printed by an earlier run
    # (``<account>/<run-id>/<checkpoint>``). Empty = start from the base model.
    resume_from: str = ""

    # --- Promotion ----------------------------------------------------------
    # Promote the final checkpoint into a servable Fireworks model. The run id
    # is appended so repeated runs do not collide.
    promote: bool = True
    output_model_id: str = "serverless-dpo-ultrafeedback"

    # --- Generation comparison ----------------------------------------------
    # Sample the frozen reference (base) and the final checkpoint side by side
    # on fresh prompts at the end of the run.
    compare_generations: bool = True

    # --- Held-out evaluation ------------------------------------------------
    # Reserve this many rows from the END of the dataset as a held-out eval
    # set; the run reports mean policy preference margin on them before vs
    # after training. 0 disables.
    eval_pairs: int = 4

    # --- WandB --------------------------------------------------------------
    # Set wandb_entity to enable Weights & Biases logging (offline mode when
    # WANDB_API_KEY is unset). Empty entity disables WandB.
    wandb_entity: str = ""
    wandb_project: str = "serverless-dpo"
    wandb_run_name: str = ""

    # --- Connection ---------------------------------------------------------
    # The "/training/v1/serverless" suffix is added automatically.
    api_base_url: str = field(
        default_factory=lambda: os.environ.get("FIREWORKS_BASE_URL", "https://api.fireworks.ai")
    )
    api_key: str = field(default_factory=lambda: os.environ.get("FIREWORKS_API_KEY", ""))

    # --- Bookkeeping --------------------------------------------------------
    dcp_timeout_s: float = 900.0
    ref_timeout_s: float = 600.0
    run_dir: str = ""
    # Requires matplotlib; set False (or don't install it) to skip the plot.
    plot_metrics: bool = True


def _validate_config(cfg: Config) -> None:
    if cfg.lora_rank <= 0:
        raise ValueError("serverless training requires lora_rank > 0 (the pool is LoRA-only)")
    if cfg.max_seq_len <= 0:
        raise ValueError("serverless training requires max_seq_len > 0")
    if cfg.steps <= 0:
        raise ValueError("steps must be > 0")
    if cfg.batch_size <= 0:
        raise ValueError("batch_size must be > 0")
    if not 0 < cfg.dpo_beta < 0.5:
        raise ValueError("dpo_beta must be > 0 and < 0.5")
    if cfg.dcp_save_interval < 0:
        raise ValueError("dcp_save_interval must be >= 0 (0 disables periodic checkpoints)")
    if cfg.ref_concurrency <= 0:
        raise ValueError("ref_concurrency must be > 0")
    if cfg.eval_pairs < 0:
        raise ValueError("eval_pairs must be >= 0 (0 disables the held-out eval)")
    for name in (cfg.checkpoint_name, cfg.final_checkpoint_name, cfg.reference_checkpoint_name):
        if not name:
            raise ValueError("checkpoint names must not be empty")
        if len(name) > MAX_CHECKPOINT_NAME_LEN:
            raise ValueError(
                f"checkpoint name {name!r} is {len(name)} characters; the promotable "
                f"checkpoint id must fit in 63 characters, so names are capped at "
                f"{MAX_CHECKPOINT_NAME_LEN}"
            )


def _validate_datum_length(datum_length: int, max_seq_len: int) -> None:
    if datum_length > max_seq_len:
        raise ValueError(
            f"training datum length {datum_length} exceeds max_seq_len {max_seq_len}"
        )


def _serverless_base_url(base_url: str) -> str:
    """Serverless training + sampling both hang off ``/training/v1/serverless``."""
    root = base_url.rstrip("/")
    if root.endswith("/training/v1/serverless"):
        return root
    if root.endswith("/training/v1"):
        return f"{root}/serverless"
    return f"{root}/training/v1/serverless"


def _control_plane_base_url(base_url: str) -> str:
    """Checkpoint list/promote use the regular API, not the serverless surface."""
    root = base_url.rstrip("/")
    for suffix in ("/training/v1/serverless", "/training/v1"):
        if root.endswith(suffix):
            return root[: -len(suffix)]
    return root


def _load_rows(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open() as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def _fmt(value: float | None, spec: str = ".4f") -> str:
    return "n/a" if value is None else format(value, spec)


def _full_sequence_for_ref(datum: tinker.Datum) -> tinker.types.ModelInput:
    """Rebuild the raw text a datum trains on, for reference logprobs.

    A datum is the shifted next-token layout, so the final target token lives
    one past the end of the model input; appending it reconstructs the text a
    sampling client's ``compute_logprobs`` can score.
    """
    target_tokens = datum.loss_fn_inputs["target_tokens"].data
    if target_tokens:
        return datum.model_input.append_int(int(target_tokens[-1]))
    return datum.model_input


def _align_reference_logprobs(
    full_sequence_logprobs: list[float | None],
    datum_length: int,
) -> list[float]:
    """Align ``compute_logprobs`` output with the trainer-forward layout.

    ``compute_logprobs`` puts ``None`` at index 0; slicing it off yields entry
    ``j`` = logprob of the token predicted at position ``j``, which is what
    ``make_batch_dpo_loss_fn`` expects for its reference arrays.
    """
    if len(full_sequence_logprobs) != datum_length + 1:
        raise ValueError(
            f"reference compute_logprobs returned {len(full_sequence_logprobs)} positions "
            f"for a {datum_length}-token datum; expected {datum_length + 1}"
        )
    aligned = full_sequence_logprobs[1:]
    return [float(x) if x is not None else 0.0 for x in aligned]


def _interleave_datums(pairs: list[Any]) -> list[tinker.Datum]:
    """[chosen_0, rejected_0, chosen_1, rejected_1, ...] -- the layout
    ``make_batch_dpo_loss_fn`` pairs by index."""
    datums: list[tinker.Datum] = []
    for pair in pairs:
        datums.append(pair.chosen_datum)
        datums.append(pair.rejected_datum)
    return datums


def _split_train_eval(
    rows: list[dict[str, Any]], eval_pairs: int
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Split off the LAST ``eval_pairs`` rows as the held-out eval set."""
    if eval_pairs == 0:
        return rows, []
    if eval_pairs >= len(rows):
        raise ValueError(
            f"eval_pairs ({eval_pairs}) must be smaller than the dataset ({len(rows)} rows)"
        )
    return rows[:-eval_pairs], rows[-eval_pairs:]


def _comparison_prompt_messages(row: dict[str, Any]) -> list[dict[str, Any]] | None:
    """The shared prompt of a preference row (everything but the final
    assistant turn), used for the generation comparison."""
    normalized = normalize_preference_row(row)
    if normalized is None:
        return None
    messages = normalized["chosen"].get("messages") or []
    if messages and messages[-1].get("role") == "assistant":
        return messages[:-1]
    return None


def _validate_resume_reference(reference: str) -> None:
    """Resume refs must name a numbered checkpoint (``<name>-<step>``).

    Final/sampler checkpoints (e.g. ``dpo-final``) carry no step suffix and
    are not resumable; accepting them silently would restart the step counter
    and dataset cursor at 0.
    """
    tail = reference.rstrip("/").split("/")[-1]
    suffix = tail.rsplit("-", 1)[-1] if "-" in tail else ""
    if not suffix.isdigit():
        raise ValueError(
            f"--resume-from must name a numbered checkpoint like 'dpo-0008' "
            f"(got {reference!r}); final/sampler checkpoints are not resumable"
        )


class ServerlessUltraFeedbackDPO:
    """One serverless DPO run over an UltraFeedback preference dataset."""

    def __init__(self, cfg: Config) -> None:
        self.cfg = cfg
        _validate_config(cfg)
        dataset_path = Path(cfg.dataset)
        if not dataset_path.exists():
            raise SystemExit(
                f"dataset not found: {cfg.dataset}\n"
                "Generate the default UltraFeedback data first: "
                "python -m examples.serverless_dpo.prepare_data"
            )
        all_rows = _load_rows(dataset_path)
        if not all_rows:
            raise SystemExit(f"dataset is empty: {cfg.dataset}")
        self.rows, self.eval_rows = _split_train_eval(all_rows, cfg.eval_pairs)

        renderer_name = cfg.renderer_name or resolve_renderer_name(cfg.tokenizer_model)
        self.tokenizer = get_tokenizer(cfg.tokenizer_model)
        self.renderer = build_renderer(
            self.tokenizer, cfg.tokenizer_model, renderer_name
        )

        # The one connection that gives us both training and sampling clients.
        self.service = FiretitanServiceClient(
            api_key=cfg.api_key,
            base_url=_serverless_base_url(cfg.api_base_url),
        )

        # Resume vs fresh start. Resuming derives base_model / lora_rank from
        # the checkpoint itself, so a resumed run cannot silently disagree
        # with the run that wrote it.
        self.start_step = 0
        self.base_model = cfg.base_model
        if cfg.resume_from:
            _validate_resume_reference(cfg.resume_from)
            print(f"resuming from checkpoint: {cfg.resume_from}", flush=True)
            t0 = time.time()
            self.training_client = self.service.create_training_client_from_state_with_optimizer(
                cfg.resume_from
            )
            self.start_step = _step_from_checkpoint_name(cfg.resume_from)
            # The checkpoint is the source of truth for the base model --
            # promote and the log line must use it, not the CLI default.
            weights_info = self.service.create_rest_client().get_weights_info_by_tinker_path(
                cfg.resume_from
            ).result()
            self.base_model = weights_info.base_model
            print(
                f"resumed in {time.time() - t0:.1f}s; continuing at step {self.start_step} "
                f"on base model {self.base_model}",
                flush=True,
            )
        else:
            self.training_client = self.service.create_lora_training_client(
                base_model=cfg.base_model,
                rank=cfg.lora_rank,
            )

        # Frozen DPO reference: snapshot the current weights and serve them
        # for the whole run. On a fresh run the LoRA is zero-init, so the
        # snapshot IS the base model (Tinker's anchor). On a resumed run the
        # reference re-anchors at the resumed weights, matching Tinker's
        # resume path.
        t0 = time.time()
        ref_result = self.training_client.save_weights_for_sampler(
            cfg.reference_checkpoint_name
        ).result(timeout=cfg.dcp_timeout_s)
        ref_path = getattr(ref_result, "path", None)
        if not ref_path:
            raise RuntimeError(
                f"save_weights_for_sampler({cfg.reference_checkpoint_name!r}) returned no path"
            )
        self.reference_path = ref_path
        self.reference_client = self.service.create_sampling_client(
            model_path=ref_path, tokenizer=self.tokenizer
        )
        # On a fresh run the reference IS the base model (zero-init LoRA); on
        # resume it re-anchors at the resumed weights. Label it honestly.
        self.reference_label = (
            "base (reference)" if not cfg.resume_from else f"reference (resumed at step {self.start_step})"
        )
        print(
            f"reference model: {ref_path} (snapshot in {time.time() - t0:.1f}s)",
            flush=True,
        )

        self.run_dir = (
            Path(cfg.run_dir).resolve()
            if cfg.run_dir
            else Path("/tmp") / f"serverless_uf_dpo_{int(time.time())}"
        )
        self.run_dir.mkdir(parents=True, exist_ok=True)
        self.metrics_path = self.run_dir / "metrics.jsonl"
        # Restore the dataset cursor so a resumed run does not re-see rows.
        self.row_cursor = self.start_step * cfg.batch_size
        self.saved_checkpoints: list[str] = []
        # The reference is frozen, so its logprobs for a row never change --
        # cache them instead of re-scoring on wrap-around.
        self._ref_cache: dict[int, tuple[list[float], list[float]]] = {}

        self.session_name = getattr(self.service, "training_session_name", None)
        self.session_id = getattr(self.service, "training_session_id", None)
        self.run_id = getattr(self.training_client, "run_id", None)
        if not self.session_id:
            raise RuntimeError(
                "serverless service did not expose a training_session_id; "
                "cannot list or promote checkpoints for this run"
            )
        print(
            f"connected serverless session={self.session_name or self.session_id} run={self.run_id}\n"
            f"base_model={self.base_model} tokenizer={cfg.tokenizer_model} renderer={renderer_name}\n"
            f"steps={cfg.steps} batch_size={cfg.batch_size} pairs lora_rank={cfg.lora_rank} "
            f"lr={cfg.learning_rate} beta={cfg.dpo_beta} max_seq_len={cfg.max_seq_len} "
            f"dcp_save_interval={cfg.dcp_save_interval}\n"
            f"rows={len(self.rows)} train + {len(self.eval_rows)} held-out eval, run_dir={self.run_dir}",
            flush=True,
        )
        setup_wandb(
            WandBConfig(
                entity=cfg.wandb_entity or None,
                project=cfg.wandb_project,
                run_name=cfg.wandb_run_name or None,
            ),
            {
                "base_model": self.base_model,
                "lora_rank": cfg.lora_rank,
                "learning_rate": cfg.learning_rate,
                "dpo_beta": cfg.dpo_beta,
                "batch_size": cfg.batch_size,
                "steps": cfg.steps,
                "max_seq_len": cfg.max_seq_len,
                "train_rows": len(self.rows),
                "eval_rows": len(self.eval_rows),
                "resume_from": cfg.resume_from or None,
            },
        )

    # -- data ----------------------------------------------------------------

    def _next_batch(self) -> list[tuple[int, dict[str, Any]]]:
        """Take the next ``batch_size`` rows (with dataset indices), wrapping
        around so the bundled sample supports a multi-step run."""
        batch = [
            ((self.row_cursor + i) % len(self.rows), self.rows[(self.row_cursor + i) % len(self.rows)])
            for i in range(self.cfg.batch_size)
        ]
        self.row_cursor += self.cfg.batch_size
        return batch

    def _render_pair(self, row: dict[str, Any]) -> Any:
        """Normalize a JSONL row and render both sides of the preference pair
        (prompt tokens weighted 0, response tokens weighted 1)."""
        normalized = normalize_preference_row(row)
        if normalized is None:
            raise ValueError(
                "row does not match any supported preference schema "
                "(chosen/rejected, samples, or OpenAI preference)"
            )
        rendered = render_preference_pair(
            normalized["chosen"],
            normalized["rejected"],
            renderer=self.renderer,
            tokenizer=self.tokenizer,
            max_seq_len=self.cfg.max_seq_len,
        )
        if rendered is None:
            raise ValueError(
                "preference pair failed to render (empty messages or over max_seq_len)"
            )
        _validate_datum_length(len(rendered.chosen_tokens), self.cfg.max_seq_len)
        _validate_datum_length(len(rendered.rejected_tokens), self.cfg.max_seq_len)
        return rendered

    # -- reference logprobs ---------------------------------------------------

    def _ref_logprobs_for_pairs(
        self, indexed_pairs: list[tuple[int, Any]]
    ) -> dict[int, tuple[list[float], list[float]]]:
        """Frozen-reference logprobs for each pair, keyed by dataset row index.

        At most ``ref_concurrency`` compute_logprobs calls are in flight at a
        time; results are cached per row across wrap-arounds.
        """
        cfg = self.cfg
        results: dict[int, tuple[list[float], list[float]]] = {}
        missing: list[tuple[int, Any]] = []
        queued: set[int] = set()
        for idx, pair in indexed_pairs:
            if idx in results or idx in queued:
                continue
            if idx in self._ref_cache:
                results[idx] = self._ref_cache[idx]
            else:
                missing.append((idx, pair))
                queued.add(idx)

        # Two calls per pair (chosen + rejected), chunked so at most
        # ref_concurrency calls are outstanding at once.
        work = [
            (idx, side, datum)
            for idx, pair in missing
            for side, datum in (("chosen", pair.chosen_datum), ("rejected", pair.rejected_datum))
        ]
        scored: dict[tuple[int, str], list[float]] = {}
        chunk = max(1, cfg.ref_concurrency)
        with warnings.catch_warnings():
            # The SDK warns against sampling-client logprobs in favor of
            # training_client.forward(). Here the sampling client is the point:
            # it serves the frozen step-0 snapshot, while the training client
            # only ever sees the *moving* policy.
            warnings.simplefilter("ignore", UserWarning)
            for start in range(0, len(work), chunk):
                futures = [
                    (idx, side, datum, self.reference_client.compute_logprobs(_full_sequence_for_ref(datum)))
                    for idx, side, datum in work[start : start + chunk]
                ]
                for idx, side, datum, future in futures:
                    scored[(idx, side)] = _align_reference_logprobs(
                        future.result(timeout=cfg.ref_timeout_s),
                        datum.model_input.length,
                    )
        for idx, _pair in missing:
            entry = (scored[(idx, "chosen")], scored[(idx, "rejected")])
            self._ref_cache[idx] = entry
            results[idx] = entry
        return results

    # -- checkpoints ---------------------------------------------------------

    def _save_dcp(self, step: int) -> str:
        """Save full trainer state (weights + optimizer) -- the checkpoint you
        resume from, distinct from the servable ``save_weights_for_sampler``
        snapshots."""
        name = f"{self.cfg.checkpoint_name}-{step:04d}"
        t0 = time.time()
        self.training_client.save_state(name).result(timeout=self.cfg.dcp_timeout_s)
        self.saved_checkpoints.append(name)
        print(f"  saved checkpoint {name!r} ({time.time() - t0:.1f}s)", flush=True)
        return name

    # -- held-out evaluation ---------------------------------------------------

    def _held_out_margin(self) -> float | None:
        """Mean policy preference margin on the held-out pairs via a plain
        ``forward`` (no backward): summed logprob of chosen minus rejected per
        pair. Positive and rising means the policy is learning the preference.
        """
        if not self.eval_rows:
            return None
        pairs = [self._render_pair(row) for row in self.eval_rows]
        datums = _interleave_datums(pairs)
        fwd = self.training_client.forward(datums, "cross_entropy").result()
        total = 0.0
        for i, pair in enumerate(pairs):
            # Same off-by-one as make_batch_dpo_loss_fn: logprob[j] predicts
            # token[j+1], so the first response logprob sits at rs - 1.
            lp_start = max(0, pair.response_start - 1)
            chosen_lp = sum(fwd.loss_fn_outputs[2 * i]["logprobs"].data[lp_start:])
            rejected_lp = sum(fwd.loss_fn_outputs[2 * i + 1]["logprobs"].data[lp_start:])
            total += chosen_lp - rejected_lp
        return total / len(pairs)

    # -- loop ----------------------------------------------------------------

    def _step(self, step: int) -> dict[str, Any]:
        t0 = time.time()
        cfg = self.cfg

        batch = self._next_batch()
        pairs = [(idx, self._render_pair(row)) for idx, row in batch]
        ref_map = self._ref_logprobs_for_pairs(pairs)
        rendered_pairs = [pair for _, pair in pairs]

        # One DPO update: policy logprobs come from the forward pass itself;
        # the loss callback scores them against the frozen reference arrays.
        datums = _interleave_datums(rendered_pairs)
        loss_fn = make_batch_dpo_loss_fn(
            [ref_map[idx][0] for idx, _ in pairs],
            [ref_map[idx][1] for idx, _ in pairs],
            [p.response_start for p in rendered_pairs],
            cfg.dpo_beta,
        )
        fb = self.training_client.forward_backward_custom(datums, loss_fn).result()
        adam = tinker.AdamParams(
            learning_rate=cfg.learning_rate,
            beta1=0.9,
            beta2=0.95,
            eps=1e-12,
            weight_decay=0.0,
        )
        self.training_client.optim_step(adam).result()

        fb_metrics = getattr(fb, "metrics", None) or {}
        rec = {
            "step": step,
            "train/step": step,  # wandb maps train/* and perf/* onto this x-axis
            "train/dpo_loss": fb_metrics.get("dpo_loss"),
            "train/margin": fb_metrics.get("margin"),
            "train/accuracy": fb_metrics.get("accuracy"),
            "train/chosen_reward": fb_metrics.get("chosen_reward"),
            "train/rejected_reward": fb_metrics.get("rejected_reward"),
            "train/pairs": len(rendered_pairs),
            "perf/ref_cache_size": len(self._ref_cache),
            "perf/step_wall_time": time.time() - t0,
        }
        with self.metrics_path.open("a") as f:
            f.write(json.dumps(rec) + "\n")
        wandb_log(rec, step)
        print(
            f"step {step:02d} dpo_loss={_fmt(rec['train/dpo_loss'])} "
            f"margin={_fmt(rec['train/margin'], '+.4f')} "
            f"acc={_fmt(rec['train/accuracy'], '.1%')} "
            f"rewards={_fmt(rec['train/chosen_reward'], '+.3f')}/{_fmt(rec['train/rejected_reward'], '+.3f')} "
            f"elapsed={rec['perf/step_wall_time']:.1f}s",
            flush=True,
        )
        return rec

    def run(self) -> list[dict[str, Any]]:
        cfg = self.cfg
        records: list[dict[str, Any]] = []

        # Held-out baseline BEFORE any optimizer step.
        margin_before = self._held_out_margin()
        if margin_before is not None:
            print(f"held-out preference margin before training: {margin_before:+.4f}", flush=True)
            wandb_log({"eval/margin_before": margin_before, "train/step": self.start_step}, self.start_step)

        # Checkpoints save at the START of a step, before its
        # forward_backward, so the saved state is exactly the weights this
        # step is about to measure.
        try:
            for step in range(self.start_step, self.start_step + cfg.steps):
                if cfg.dcp_save_interval and step > self.start_step and step % cfg.dcp_save_interval == 0:
                    self._save_dcp(step)
                records.append(self._step(step))

            # Held-out eval AFTER the last optimizer step, on the same pairs.
            margin_after = self._held_out_margin()
            if margin_before is not None and margin_after is not None:
                final_step = self.start_step + cfg.steps
                print(
                    f"held-out preference margin after training:  {margin_after:+.4f} "
                    f"(delta {margin_after - margin_before:+.4f})",
                    flush=True,
                )
                wandb_log(
                    {
                        "eval/margin_after": margin_after,
                        "eval/margin_delta": margin_after - margin_before,
                        "train/step": final_step,
                    },
                    final_step,
                )

            # Final full-state checkpoint: what --resume-from consumes.
            final_step = self.start_step + cfg.steps
            final_dcp = self._save_dcp(final_step)
            resume_ref = self._resume_reference(final_dcp)
            print(f"\nresume this run with:\n  --resume-from {resume_ref}", flush=True)

            # Final sampler checkpoint: servable, listable, and promotable.
            final = self.training_client.save_weights_for_sampler(cfg.final_checkpoint_name).result()
            snapshot = getattr(final, "path", None)
            if not snapshot:
                raise RuntimeError(
                    f"save_weights_for_sampler({cfg.final_checkpoint_name!r}) returned no path"
                )
            print(f"final sampler checkpoint: {snapshot}", flush=True)

            self._compare_generations(snapshot)

            if cfg.promote:
                self._promote()
        finally:
            self.reference_client.close()

        losses = [r["train/dpo_loss"] for r in records if r["train/dpo_loss"] is not None]
        margins = [r["train/margin"] for r in records if r["train/margin"] is not None]
        if losses:
            print(
                f"\ndpo_loss: {losses[0]:.4f} -> {losses[-1]:.4f} "
                f"margin: {margins[0]:+.4f} -> {margins[-1]:+.4f} "
                f"over {len(records)} steps",
                flush=True,
            )
        if cfg.plot_metrics:
            self._plot(records)
        wandb_finish()
        print(f"metrics: {self.metrics_path}", flush=True)
        return records

    def _resume_reference(self, checkpoint_name: str) -> str:
        """The portable, cross-process checkpoint reference for --resume-from:
        ``<account>/<run-id>/<checkpoint>``."""
        account = _account_from_session(self.session_name)
        if account and self.run_id:
            return f"{account}/{self.run_id}/{checkpoint_name}"
        return checkpoint_name

    # -- generation comparison -------------------------------------------------

    def _compare_generations(self, final_path: str) -> None:
        """Sample the frozen reference vs the DPO-trained model side by side.

        The reference is the base model on a fresh run, or the resumed weights
        on a resumed run (see ``reference_label``). Checkpoint sampling is
        session-scoped, so this runs in-session against the just-saved final
        sampler checkpoint.
        """
        if not self.cfg.compare_generations:
            return
        cfg = self.cfg
        # Prefer held-out eval prompts (never trained on); fall back to train
        # rows when the eval split is disabled.
        source_rows = self.eval_rows if self.eval_rows else self.rows
        prompt_messages = []
        for row in source_rows:
            messages = _comparison_prompt_messages(row)
            if messages:
                prompt_messages.append(messages)
            if len(prompt_messages) >= 2:
                break
        if not prompt_messages:
            print("generation comparison skipped: no usable prompts in dataset", flush=True)
            return

        final_sampler = self.service.create_sampling_client(
            model_path=final_path, tokenizer=self.tokenizer
        )
        try:
            for messages in prompt_messages:
                prompt = self.renderer.build_generation_prompt(messages)
                params = tinker.SamplingParams(
                    max_tokens=256,
                    temperature=0.7,
                    stop=self.renderer.get_stop_sequences(),
                )
                base_resp = self.reference_client.sample(
                    prompt=prompt, num_samples=1, sampling_params=params
                ).result(timeout=cfg.ref_timeout_s)
                dpo_resp = final_sampler.sample(
                    prompt=prompt, num_samples=1, sampling_params=params
                ).result(timeout=cfg.ref_timeout_s)

                base_text = get_text_content(
                    self.renderer.parse_response(list(base_resp.sequences[0].tokens))[0]
                ).strip()
                dpo_text = get_text_content(
                    self.renderer.parse_response(list(dpo_resp.sequences[0].tokens))[0]
                ).strip()
                prompt_text = str(messages[-1].get("content", ""))[:200]
                print(
                    f"\n=== generation comparison ===\n"
                    f"prompt: {prompt_text}\n"
                    f"--- {self.reference_label} ---\n{base_text}\n"
                    f"--- after DPO ---\n{dpo_text}\n",
                    flush=True,
                )
                with self.metrics_path.open("a") as f:
                    f.write(json.dumps({
                        "comparison/prompt": prompt_text,
                        "comparison/base_response": base_text,
                        "comparison/dpo_response": dpo_text,
                    }) + "\n")
        finally:
            final_sampler.close()

    # -- promote -------------------------------------------------------------

    def _promote(self) -> str | None:
        """List the session's checkpoints and promote the final one to a model.

        Promotion uses the session-scoped control-plane endpoints, not the
        serverless training surface, so it goes through a separate REST client.
        """
        cfg = self.cfg
        cp_client = FireworksClient(
            api_key=cfg.api_key,
            base_url=_control_plane_base_url(cfg.api_base_url),
        )
        try:
            session_name = self.session_name or (
                f"accounts/{cp_client.account_id}/trainingSessions/{self.session_id}"
            )
            checkpoints = cp_client.list_training_session_checkpoints(session_name)
            match = _find_promotable(checkpoints, cfg.final_checkpoint_name, self.run_id)
            if match is None:
                labels = [
                    f"{_checkpoint_label(c)} promotable={c.get('promotable')}" for c in checkpoints
                ]
                print(
                    f"promote skipped: {cfg.final_checkpoint_name!r} is not listed as "
                    f"promotable yet (saw {len(checkpoints)}: {labels})",
                    flush=True,
                )
                return None

            output_model_id = _unique_model_id(cfg.output_model_id, self.run_id)
            model = cp_client.promote_session_checkpoint(
                name=match["name"],
                output_model_id=output_model_id,
                base_model=self.base_model,
            )
            model_name = model.get("name") if isinstance(model, dict) else str(model)
            print(f"promoted model: {model_name}", flush=True)
            return model_name
        finally:
            cp_client.close()

    # -- plotting ------------------------------------------------------------

    def _plot(self, records: list[dict[str, Any]]) -> None:
        try:
            import matplotlib

            matplotlib.use("Agg")
            import matplotlib.pyplot as plt
        except ImportError:
            print("matplotlib not installed; skipping metric curves", flush=True)
            return
        points = [(r["step"], r["train/dpo_loss"], r["train/margin"]) for r in records
                  if r["train/dpo_loss"] is not None and r["train/margin"] is not None]
        if not points:
            return
        steps, losses, margins = zip(*points)
        fig, ax = plt.subplots(figsize=(8, 5))
        ax.plot(steps, losses, marker="o", color="tab:red", label="dpo_loss")
        ax.set_xlabel("optimizer step")
        ax.set_ylabel("DPO loss", color="tab:red")
        ax.set_ylim(bottom=0.0)
        ax.tick_params(axis="y", labelcolor="tab:red")
        ax2 = ax.twinx()
        ax2.plot(steps, margins, marker="s", linestyle="--", color="tab:blue", label="margin")
        ax2.set_ylabel("reward margin (chosen - rejected)", color="tab:blue")
        ax2.tick_params(axis="y", labelcolor="tab:blue")
        ax.set_title(f"Serverless DPO ({self.base_model}, beta={self.cfg.dpo_beta})")
        ax.grid(True, alpha=0.3)
        fig.tight_layout()
        plot_path = self.run_dir / "dpo_curve.png"
        fig.savefig(plot_path, dpi=120)
        plt.close(fig)
        print(f"metric curves: {plot_path}", flush=True)


# -- helpers -------------------------------------------------------------------


def _account_from_session(session_name: str | None) -> str | None:
    """``accounts/{account}/trainingSessions/{id}`` -> ``{account}``."""
    parts = (session_name or "").split("/")
    if len(parts) >= 2 and parts[0] == "accounts" and parts[1]:
        return parts[1]
    return None


def _step_from_checkpoint_name(reference: str) -> int:
    """Recover the optimizer step encoded in a ``<name>-<step>`` checkpoint,
    or 0 when the reference carries no numeric suffix."""
    tail = reference.rstrip("/").split("/")[-1]
    suffix = tail.rsplit("-", 1)[-1] if "-" in tail else ""
    return int(suffix) if suffix.isdigit() else 0


def _checkpoint_label(checkpoint: dict[str, Any]) -> str:
    return str(checkpoint.get("name", "")).rstrip("/").split("/")[-1]


def _find_promotable(
    checkpoints: list[dict[str, Any]],
    final_name: str,
    run_id: str | None,
) -> dict[str, Any] | None:
    """The listed, promotable checkpoint matching ``final_name``, tolerating
    both bare and ``{run_id}-{name}-{suffix}`` id shapes."""
    prefixes = [final_name]
    if run_id:
        prefixes.append(f"{run_id}-{final_name}")

    def matches(checkpoint: dict[str, Any]) -> bool:
        label = _checkpoint_label(checkpoint)
        return any(label == p or label.startswith(p + "-") for p in prefixes)

    return next((c for c in checkpoints if matches(c) and bool(c.get("promotable"))), None)


def _unique_model_id(base_id: str, run_id: str | None) -> str:
    suffix = str(run_id or "").replace("run-", "")[:8]
    if not suffix:
        return base_id[:63]
    return f"{base_id[: 63 - len(suffix) - 1]}-{suffix}"


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--base-model", default=Config.base_model)
    p.add_argument("--tokenizer-model", default=Config.tokenizer_model)
    p.add_argument("--renderer-name", default=Config.renderer_name)
    p.add_argument("--dataset", default=Config.dataset)
    p.add_argument("--lora-rank", type=int, default=Config.lora_rank)
    p.add_argument("--max-seq-len", type=int, default=Config.max_seq_len)
    p.add_argument("--steps", type=int, default=Config.steps)
    p.add_argument("--batch-size", type=int, default=Config.batch_size)
    p.add_argument("--learning-rate", type=float, default=Config.learning_rate)
    p.add_argument("--dpo-beta", type=float, default=Config.dpo_beta)
    p.add_argument("--ref-concurrency", type=int, default=Config.ref_concurrency)
    p.add_argument(
        "--eval-pairs",
        type=int,
        default=Config.eval_pairs,
        help="Rows reserved from the dataset tail as held-out eval (0 disables).",
    )
    p.add_argument("--wandb-entity", default=Config.wandb_entity,
                   help="WandB entity/team; enables WandB logging when set.")
    p.add_argument("--wandb-project", default=Config.wandb_project)
    p.add_argument("--wandb-run-name", default=Config.wandb_run_name)
    p.add_argument(
        "--dcp-save-interval",
        type=int,
        default=Config.dcp_save_interval,
        help="Save a resumable checkpoint every N steps (0 disables periodic saves).",
    )
    p.add_argument(
        "--resume-from",
        default=Config.resume_from,
        help="Checkpoint reference from an earlier run: '<account>/<run-id>/<checkpoint>'.",
    )
    p.add_argument("--output-model-id", default=Config.output_model_id)
    p.add_argument("--no-promote", action="store_false", dest="promote", default=Config.promote)
    p.add_argument("--no-compare", action="store_false", dest="compare_generations",
                   default=Config.compare_generations,
                   help="Skip the end-of-run base-vs-DPO generation comparison.")
    p.add_argument("--run-dir", default=Config.run_dir)
    p.add_argument("--no-plot", action="store_false", dest="plot_metrics", default=Config.plot_metrics)
    return p.parse_args(argv)


def config_from_args(args: argparse.Namespace) -> Config:
    return Config(
        base_model=args.base_model,
        tokenizer_model=args.tokenizer_model,
        renderer_name=args.renderer_name,
        dataset=args.dataset,
        lora_rank=args.lora_rank,
        max_seq_len=args.max_seq_len,
        steps=args.steps,
        batch_size=args.batch_size,
        learning_rate=args.learning_rate,
        dpo_beta=args.dpo_beta,
        ref_concurrency=args.ref_concurrency,
        eval_pairs=args.eval_pairs,
        wandb_entity=args.wandb_entity,
        wandb_project=args.wandb_project,
        wandb_run_name=args.wandb_run_name,
        dcp_save_interval=args.dcp_save_interval,
        resume_from=args.resume_from,
        promote=args.promote,
        output_model_id=args.output_model_id,
        compare_generations=args.compare_generations,
        run_dir=args.run_dir,
        plot_metrics=args.plot_metrics,
    )


def main(cfg: Config) -> list[dict[str, Any]]:
    if not cfg.api_key:
        raise SystemExit("FIREWORKS_API_KEY is required (export it or set Config.api_key)")
    return ServerlessUltraFeedbackDPO(cfg).run()


if __name__ == "__main__":
    # Fork this: point `dataset` at your own preference JSONL, swap
    # `base_model` / `tokenizer_model`, and tune beta / lr / the loop shape.
    main(config_from_args(parse_args()))
