version: ??

working_dir: /mnt/text/model/${model.name}/${data.name}/${version}
output_model_dir: ${working_dir}/final

wandb_key: null
wandb_project: null

hydra:
  run:
    dir: ${working_dir}/conf/${now:%Y-%m-%d}_${now:%H-%M-%S}
